### ISSUE TITLE
Sinytra Connector Incompatibility - Potential Forge Port?

### ISSUE THREAD

**Issue by Snugs** [henkelmax/voicechat-interaction#12]
**Bug description**
As far as I'm aware, Simple Voice Chat is compatible with the Sinytra Connector mod for Forge, however, this mod is not.

**Steps to reproduce the issue**
1. Install NeoForge/Forge Loader
2. Install Sinytra Connector, Connector Extras, Forgified Fabric API, Simple Voice Chat, and Voice Chat Interaction
3. Go to a Deep Dark biome and attempt to talk to the skulk sensors
4. See that no sound waves are bouncing between the sensors

**Expected behavior**
I expected my voice to interact with the environment, as the symbols from Simple Voice Chat were displayed to show that I was talking.

**Log files**
I do not currently have a log file, but I can attain one if desired.

**Versions**
- Minecraft Version: 1.20.1
- NeoForge Version: 47.1.84
- Mod Version: 1.0.6

**Other mods**
As far as I'm aware, compatibility with Sinytra Connector is the issue.

**Suggested Fix**
Would it be possible for you to have a look at compatibility with Sinytra Connector or potentially a Forge port? If not, may I acquire permission from you to create a Forge port myself? I look forward to hearing from you in regards to this situation ^_^

**Comment by henkelmax** [comment]
We don't support any kind of software that attempts support for other loaders.
