### ISSUE TITLE
Crashing after disconnecting from dedicated server in 1.20.6

### ISSUE THREAD

**Issue by ZiQu-dev** [henkelmax/voicechat-interaction#13]
### Bug description

For some reason, game crashes after quitting dedicated server. Bug is present regardless of fabric-api presence. Can be only reproduced with newest game version.

I can of course provide crash-log with MixinTrace installed add a list of mixins (and Mixin configuration names) to classes in the stack trace to crash reports.

### Minecraft version

1.20.6

### Simple Voice Chat version

1.20.6-2.5.15

### Mod version

1.20.6-1.0.6

### Mod loader and version

Fabric Loader 0.15.11

### Steps to reproduce

1. Install both Simple Voice Chat and Voice Chat Interactions and place dedicated server
2. Connect to the server with Simple Voice Chat and Voice Chat Interactions both installed on both ends
3. Disconnect from server
4. Game should crash after that

### Expected behavior

Returning to Main Menu of the game.

### Log files

https://gist.github.com/ZiQu-dev/002d8e14a6df323df86bbdabeefe3a74

**Comment by henkelmax** [comment]
This is a server-side mod. It should **not** be installed on the client.

**Comment by ZiQu-dev** [comment]
You should write it up in mod description, many people like me are going to install it on client regardless of the "server side" comment in tht description. Anyway thanks for help :3

**Comment by henkelmax** [comment]
Its fixed now anyways.
