### ISSUE TITLE
How To Edit Configs?

### ISSUE THREAD

**Issue by Synth52** [henkelmax/voicechat-interaction#14]
### Bug description

I want to make it so that sensors detect you even while crouching, as it said i could change that, but mod menu doesnt let me change the configs

### Minecraft version

1.20.1

### Simple Voice Chat version

fabric-1.20.1-2.5.19

### Mod version

fabric-1.20.1-1.0.6

### Mod loader and version

Fabric Loader ____

### Steps to reproduce

1. have vc vci and mod menu installed
2. try to change the configuration in the in game mod menu

### Expected behavior

show a bunch of options and configurations i can change

### Log files

idk

**Comment by henkelmax** [comment]
Read the mod description! Also this is for bugs and not for general help!
