### ISSUE TITLE
Why is this mod fabric only?

### ISSUE THREAD

**Issue by vinnyg0621** [henkelmax/voicechat-interaction#15]
### Bug description

i'm curious to why this mod is only for fabric and quilt, but no forge? what the??

### Minecraft version

1.20.1

### Simple Voice Chat version

every one

### Mod version

1.20.1 - all

### Mod loader and version

Forge 1.20.1 - 47.3.5

### Steps to reproduce

1. ask for a forge port
2. but you tell me no?
3. and you won't tell me why??

### Expected behavior

plz tell me why you won't ever support forge, I'm so curious!

### Log files

i don't have a log, i am just curious.

**Comment by henkelmax** [comment]
https://github.com/henkelmax/voicechat-interaction/issues/9#issuecomment-2269591166
