### ISSUE TITLE
Voice chat interaction doesn't work with sinytra connector on neoforge environment

### ISSUE THREAD

**Issue by lzm11111111** [henkelmax/voicechat-interaction#16]
### Bug description

When installed voice chat ineraction on neoforge 1.21.x with sinytra connector, the game don't crash, but when I talking in the game, the sculk sensor doesn't trigged and warden don't get alerted. It works fine on fabric environment

### Minecraft version

1.21.1

### Simple Voice Chat version

1.21.1-2.5.24

### Mod version

1.21.1-1.0.8

### Mod loader and version

Neoforge 21.1.65

### Steps to reproduce

1. Installing simple voice chat, voice chat interaction and sinytra connector on neoforge client
2. Launch the game
3. Place a sculk sensor
4. Talk to sculk sensor
5. The sculk sensor doesn't trigged

### Expected behavior

I expect the sculk sensor get trigged while talk to sculk sensor, like on fabric environment

### Log files

I do not currently have a log file

**Comment by henkelmax** [comment]
We don't support hybrid loaders. Its a fabric mod. Report it to the sinytra devs. We won't fix it!
