### ISSUE TITLE
Shifting without wispering donsen't trigger sound

### ISSUE THREAD

**Issue by Kysha7** [henkelmax/voicechat-interaction#2]
**Bug description**
In the config file you can choose if "sneak_interaction" should trigger vibrations or not. I choose put that in "true", but when I speak while shifting, donsen't trigger.

**Steps to reproduce the issue**
Turn the option "sneak_interaction" into "true" and then shift and speak normal, vibrations donsen't show and sensor don't do sound.

**Expected behavior**
With the option in true, speak while shifting should trigger the sensor.

**Log files**
There is no logs. In this case, the plugin work almost perfect, I can press the wisper button and no vibration show up, I can speak normal and hear me

**Versions**
- Version of the server "purpur-1.19-1718"
- Fabric loader version: NONE I use the plugin.
- Version of the plugin voicechat-interaction-paper-1.0.0

**Other mods**
Again, I use the plugin.

**Screenshots (Optional)**
NONE

**Comment by henkelmax** [comment]
Wrong bugtracker.
https://github.com/iGalaxyYT/voicechat-interaction-paper
