### ISSUE TITLE
(Feature Request) - toggle interaction option / new config entry

### ISSUE THREAD

**Issue by FixingGlobe** [henkelmax/voicechat-interaction#3]
**Bug description**
Command for toggling the interaction on and off / or a config setting like - "normal voice interaction = true" by default

**Steps to reproduce the issue**
Not a bug but a suggestion

**Expected behavior**
Since the voice chat interaction is fun when someone is streaming, but not elsewhere I would like to ask if it is possible to add a command which allows all interactions with voice chat to be disabled at any time?
Or if that's not possible, if it would be possible to add a line in config to disable it interacting with the normal voice, so only a server restart and a quick edit in the config is required instead of pulling the mod from the server and if needed moving it into the mods folder again. (And this also allows some weird customization like it only interacting while whispering.)

**Log files**
Thank you for your awesome work :)

**Comment by henkelmax** [comment]
https://github.com/henkelmax/voicechat-interaction#config-values

You can just set the threshold to a really high value.

**Comment by FixingGlobe** [comment]
I did try that like 250 dB and I was still able to trigger it with a +30 dB microphone amplification and later even 9000 db.

**Comment by FixingGlobe** [comment]
I try again just to be sure

**Comment by FixingGlobe** [comment]
(+)250 dB is reacting to my microphone with +30dB amplification and there is for sure no way it's possible that it is even close to 250 dB. And for sure no-one is driving their microphone at such unrealistic values, but it still interacts even at such values. For me personally it's not an issue but a one size fits all solution would be beneficial.

**Comment by henkelmax** [comment]
Alright, then just remove the mod to disable the feature, since you need to restart the server anyways. I don't see the point in a config option disabling the only feature of a mod.

**Comment by FixingGlobe** [comment]
It would be a nice gimmick, but it's not really the goal to make the menus bloated for some really loud microphones users.
The question may come up at a future point that's why I'm asking, but for me setting it at 250 dB is working for my users.
Also sorry for bothering you

**Comment by FixingGlobe** [comment]
> Alright, then just remove the mod to disable the feature, since you need to restart the server anyways. I don't see the point in a config option disabling the only feature of a mod.

Also this 😂
