### ISSUE TITLE
Falling blocks sometimes not removed

### ISSUE THREAD

**Issue by joeyleesi** [henkelmax/voicechat-interaction#4]
**Bug description**
When breaking a block supporting a falling block, the falling block sometimes isn't removed. This leaves behind a block that can't be interacted with (the player can walk through it but can't place a block in the same spot). The falling block is serverside and not a typical ghost block as other players on the server see the same block. This can happen at any time, but I've detailed a somewhat reliable way to reproduce the bug below.  This happens to players periodically while mining sand, gravel, or an anvil breaking in an anvil stack.

**Steps to reproduce the issue**
1. Create a fabric server using `fabric-server-mc.1.19.2-loader.0.14.10-launcher.0.11.1.jar`
2. Install the following mods:
    - fabric-api-0.64.0+1.19.2.jar
    - vcinteraction-1.19.2-1.0.2.jar
    - voicechat-fabric-1.19.2-2.3.13.jar
3. Start the server
     e.g. `java -Xmx2G -jar fabric-server-mc.1.19.2-loader.0.14.10-launcher.0.11.1.jar nogui` 
4. Break the supporting blocks of gravity blocks. For example, I made this setup by having the following command blocks:
```mcfunction
# Command Block 1 (right-most in pic)
fill 99 105 160 167 105 120 torch

# Command Block 2 (center in pic)
fill 99 110 160 167 115 120 sand

# Command Block 3 (left-most in pic)
fill 99 105 160 167 105 120 air

# Repeating Command Block to kill sand drops as to not crash the server
kill @e[type=item]
```
![Testing Setup](https://user-images.githubusercontent.com/98718890/203664188-56521677-badb-4d4b-9f23-8fce8fb5fd93.png)

6. Look for the glitched falling blocks. Seems to always take two presses for it to happen. You can see an example of one in the top left of the stone platform in the above pic

**Expected behavior**
The falling block should be removed.

**Log files**
[https://mclo.gs/o4aF5nH](https://mclo.gs/o4aF5nH).

**Versions**
- Minecraft version: `1.19.2`
- Fabric loader version: `0.14.10`
- Mod version: `1.19.2-1.0.2`

**Other mods**
Only dependencies

**Screenshots**
![Screenshot of the issue](https://user-images.githubusercontent.com/98718890/203665297-cc7aa19d-d4e8-4944-8677-1bc8b0d2acd4.png)

**Comment by henkelmax** [comment]
I tested it with your exact setup and I can't see any falling sand blocks being left.

**Comment by joeyleesi** [comment]
The only thing I can think of that might be different from our setups is the hardware. Maybe it has something to do with the amount of lag. [Here is a video](https://drive.google.com/file/d/1ZLbJl-uOxYpZxL32T2CddJ8r7EjcLYZc/preview) to hopefully better show the issue. If you want me to test anything else, let me know, and I'm happy to do so.

It seems weird that vc-interaction would have anything to do with this issue, but the only way I've been able to reproduce it is with the mod enabled.

**Comment by henkelmax** [comment]
It might also be Polymer, which is packed into the mod.
Please remove all mods and just install [this](https://modrinth.com/mod/polymer/version/0.2.10%2B1.19.1) version of Polymer.

**Comment by henkelmax** [comment]
Yep it actually was a polymer issue:
https://github.com/Patbox/polymer/commit/27b635ce6667393d042c5a9f755258adaf66d720
