### ISSUE TITLE
Make this a Bukkit/Spigot plugin.

### ISSUE THREAD

**Issue by MagmaSlime123** [henkelmax/voicechat-interaction#5]
Since no suggestion template or Discord exists, then I'm leaving this here. Don't get pissed at me.

As the title says, make this into an addon for SVC's plugin.

**Comment by henkelmax** [comment]
https://github.com/iGalaxyYT/voicechat-interaction-paper

**Comment by MagmaSlime123** [comment]
Sorry, didn't know a port existed.
