### ISSUE TITLE
Could you make your Plugin available for Aternos?

### ISSUE THREAD

**Issue by Minoxxe** [henkelmax/voicechat-interaction#6]
Hello,
I know it's not a bug, but i don't know how to change the "label" (this is the first time commenting on Github). I was trying to submit your Plugin in the Aternos "Plugin suggestion" section, but unfortunately Github website is not supported. I already tried to contact Aternos support for help, but they gave me this following solution. If it doesn't bother you too much, I wanted to ask you if you could upload your Plugin to one of these websites (actually I have no idea which is the appropriate website for plugins, maybe the third one):

curseforge.com
dev.bukkit.org
spigotmc.org
poggit.pmmp.io
modrinth.com

If you have already done this, could you send me the link, so that I can submit the plugin? Thank you.

**Comment by henkelmax** [comment]
This mod (not plugin) is already available on curseforge and modrinth

**Comment by Minoxxe** [comment]
Yeah, I know there is the mod, but some months ago, on "Simple voice chat" discord server modders (I guess) told me there is "Third party Paper port".

**Comment by Minoxxe** [comment]
I'm sorry I just noticed that this is not the "Third party Paper port" comment section. Sorry for the misunderstanding.
