### ISSUE TITLE
[Question] Forge port?

### ISSUE THREAD

**Issue by DanDragonWolf** [henkelmax/voicechat-interaction#9]
Is there any possibility of a forge port? I was hoping to use this on a forge server with a few other mods.

**Comment by henkelmax** [comment]
No. This is fabric only

**Comment by NanoAi** [comment]
Any chances that this would get a NeoForge port for 1.20.X? Curious as to why this addon is Fabric only btw.

**Comment by vinnyg0621** [comment]
why is it fabric only????

**Comment by DanDragonWolf** [comment]
Was asking if yall would port it, not if it would work on forge. If you won't, why not? It should be easier to do than with most mods since all it does is connect to simple voice chat

**Comment by henkelmax** [comment]
There won't be a forge version. I simply don't want to port it to forge, thats the reason.

**Comment by Redstonedust653** [comment]
you can use Forgified Fabric API if you want to have it on forge/neo
